In [1]:
import numpy as np
import random
from random import shuffle
import tensorflow as tf

In [10]:
#将9维信息读入提取出来
def read9content(fileName):
    outfile = file(fileName[:-3]+"csv",'wb')
    with open(fileName,'rb') as f:
        for line in f:
            line = line.split('\t')
            if len(line)==12:
                for index in range(9):
                    outfile.write(line[index+2] + " ")
                outfile.write('\n')
#         if i==10:
#             break
    outfile.close()
read9content("Data160816045256.tsv")
read9content("Data160816070341.tsv")
read9content("Data161009015449.tsv")
read9content("Data161009110841.tsv")

# attension  ！！！
## 需要将生成的csv数据文件中的第一行删除

In [2]:
#处理数据 Data161009110841.csv
#得到train_input_841，train_output_841

#生成训练数据 Data161009110841.csv
# 0-15000/1  15001-39000/2 39001-46400/3
index = 0
train_data = []
with open("Data161009110841.csv","rb") as f:
    for line in f:
        if index==46400:
            break
        temp = []
        line = line.strip().split(' ')
        temp = [float(x) for x in line]
        train_data.append(temp)
        index = index +1

#将数据每20维合成一个训练样本
sequence_len = 20
train_input_841 = []     #46381 * 20 * 9
for i in range(46400-sequence_len+1):
    temp = []
    for j  in range(sequence_len):
        temp.append(train_data[i+j])
    train_input_841.append(temp)
    
    
#生成数据标签  
# 0-14980/1  14981-38980/2 38981-46381/3
train_output_841 = []  #46381 * 3
for i in range(0,14981):
    temp = []
    temp.append(1)
    temp.append(0)
    temp.append(0)
    train_output_841.append(temp)
    
for i in range(14981,38981):
    temp = []
    temp.append(0)
    temp.append(1)
    temp.append(0)
    train_output_841.append(temp)

for i in range(38981,46381):
    temp = []
    temp.append(0)
    temp.append(0)
    temp.append(1)
    train_output_841.append(temp)
    
print "train_input_841: ",len(train_input_841)
print "train_output_841: ",len(train_output_841)

train_input_841:  46381
train_output_841:  46381


In [3]:
#处理数据 Data161009015449.csv
#得到train_input_449，train_output_449

#生成训练数据 Data161009015449.csv
# 0-27900/3  51250-71800/2 71801-93059/1
train_data = []
with open("Data161009015449.csv","rb") as f:
    for line in f:
        temp = []
        line = line.strip().split(' ')
        temp = [float(x) for x in line]
        train_data.append(temp)
        
#将数据每20维合成一个训练样本
sequence_len = 20
train_input_449 = []     #69651 * 20 * 9

for i in range(0,27900-sequence_len+1):  #27881
    temp = []
    for j  in range(sequence_len):
        temp.append(train_data[i+j])
    train_input_449.append(temp)  
# print len(train_input_449)    

for i in range(51250,71800-sequence_len+1): #20531
    temp = []
    for j  in range(sequence_len):
        temp.append(train_data[i+j])
    train_input_449.append(temp)  
# print len(train_input_449) 

for i in range(71801,93059-sequence_len+1): #21239
    temp = []
    for j  in range(sequence_len):
        temp.append(train_data[i+j])
    train_input_449.append(temp)  
# print len(train_input_449) 

#生成数据标签  
# 0-27900/3  51250-71800/2 71801-93059/1
train_output_449 = []  #69651 * 3
for i in range(0,27881):
    temp = []
    temp.append(0)
    temp.append(0)
    temp.append(1)
    train_output_449.append(temp)
    
for i in range(27881,48412):
    temp = []
    temp.append(0)
    temp.append(1)
    temp.append(0)
    train_output_449.append(temp)

for i in range(48412,69651):
    temp = []
    temp.append(1)
    temp.append(0)
    temp.append(0)
    train_output_449.append(temp)
    
print "train_input_449: ",len(train_input_449)
print "train_output_449: ",len(train_output_449)

train_input_449:  69651
train_output_449:  69651


In [4]:
#处理数据 Data160816045256.csv
#得到train_input_256，train_output_256

#生成训练数据 Data160816045256.csv
# 0-15000/2 15001-44696/3
train_data = []
with open("Data160816045256.csv","rb") as f:
    for line in f:
        temp = []
        line = line.strip().split(' ')
        temp = [float(x) for x in line]
        train_data.append(temp)

#将数据每20维合成一个训练样本
sequence_len = 20
train_input_256 = []     #44657 * 20 * 9

for i in range(0,15000-sequence_len+1):  #14981
    temp = []
    for j  in range(sequence_len):
        temp.append(train_data[i+j])
    train_input_256.append(temp)  
# print len(train_input_256)

for i in range(15001,44696-sequence_len+1):  #29676
    temp = []
    for j  in range(sequence_len):
        temp.append(train_data[i+j])
    train_input_256.append(temp)  
# print len(train_input_256)

#生成数据标签  
# 0-15000/2 15001-44696/3
train_output_256 = []   #14981 * 2
for i in range(0,14981):
    temp = []
    temp.append(0)
    temp.append(1)
    temp.append(0)
    train_output_256.append(temp)
    
for i in range(14981,44657):
    temp = []
    temp.append(0)
    temp.append(0)
    temp.append(1)
    train_output_256.append(temp)
    
print "train_input_256: ",len(train_input_256)
print "train_output_256: ",len(train_output_256)

train_input_256:  44657
train_output_256:  44657


In [5]:
#处理数据 Data160816070341.csv
#得到train_input_341，train_output_341

#生成训练数据 Data160816045256.csv
# 0-66583/1 
train_data = []
with open("Data160816070341.csv","rb") as f:
    for line in f:
        temp = []
        line = line.strip().split(' ')
        temp = [float(x) for x in line]
        train_data.append(temp)
# print len(train_data)

#将数据每20维合成一个训练样本
sequence_len = 20
train_input_341 = []     #66564 * 20 * 9
for i in range(0,66583-sequence_len+1):  #14981
    temp = []
    for j  in range(sequence_len):
        temp.append(train_data[i+j])
    train_input_341.append(temp)  
# print len(train_input_341)

#生成数据标签  
# 0-66583/1 
train_output_341 = []   #66564 * 1
for i in range(0,66564):
    temp = []
    temp.append(1)
    temp.append(0)
    temp.append(0)
    train_output_341.append(temp)
print "train_input_341: ",len(train_input_341)
print "train_output_341: ",len(train_output_341)    

train_input_341:  66564
train_output_341:  66564


In [6]:
#显示四个数据集的样本数
# "Data161009110841.tsv"
# "Data161009015449.tsv"
# "Data160816045256.tsv"
# "Data160816070341.tsv"
print "train_input_841: ",len(train_input_841)
print "train_output_841: ",len(train_output_841)
print "train_input_449: ",len(train_input_449)
print "train_output_449: ",len(train_output_449)
print "train_input_256: ",len(train_input_256)
print "train_output_256: ",len(train_output_256)
print "train_input_341: ",len(train_input_341)
print "train_output_341: ",len(train_output_341)

train_input_841:  46381
train_output_841:  46381
train_input_449:  69651
train_output_449:  69651
train_input_256:  44657
train_output_256:  44657
train_input_341:  66564
train_output_341:  66564


In [7]:
#数据集合并，想用几个数据集直接相加
train_input = train_input_841 + train_input_449+train_input_341
train_output = train_output_841 + train_output_449+train_output_341
print len(train_input)

#将数据集中的数据混合打乱
index = [i for i in range(len(train_input))]    
random.shuffle(index)   
train_input1 = []
train_output1 = []
for i in index:
    train_input1.append(train_input[i])
    train_output1.append(train_output[i]) 

#分训练数据及测试数据(4:1)
NUM_EXAMPLES = len(train_input)/5
train_input = train_input1[NUM_EXAMPLES:]
train_output = train_output1[NUM_EXAMPLES:] #everything beyond 10,000
test_input = train_input1[:NUM_EXAMPLES]
test_output = train_output1[:NUM_EXAMPLES] #till 10,000

182596


In [8]:
#rnn
import tensorflow as tf
#输入输出数据
data = tf.placeholder(tf.float32, [None, 20,9]) #Number of examples, number of input, dimension of each input
target = tf.placeholder(tf.float32, [None, 3])

num_hidden = 24     
cell = tf.nn.rnn_cell.LSTMCell(num_hidden,state_is_tuple=True)
val, _ = tf.nn.dynamic_rnn(cell, data, dtype=tf.float32)
val = tf.transpose(val, [1, 0, 2])
last = tf.gather(val, int(val.get_shape()[0]) - 1)

weight = tf.Variable(tf.truncated_normal([num_hidden, int(target.get_shape()[1])]))
bias = tf.Variable(tf.constant(0.1, shape=[target.get_shape()[1]]))
prediction = tf.nn.softmax(tf.matmul(last, weight) + bias)
cross_entropy = -tf.reduce_sum(target * tf.log(prediction))   #误差函数
optimizer = tf.train.AdamOptimizer()
minimize = optimizer.minimize(cross_entropy)
mistakes = tf.not_equal(tf.argmax(target, 1), tf.argmax(prediction, 1))
error = tf.reduce_mean(tf.cast(mistakes, tf.float32))

#模型参数初始化
init_op = tf.initialize_all_variables()
sess = tf.Session()
sess.run(init_op)

#训练参数
batch_size = 1000
no_of_batches = int(len(train_input)) / batch_size
epoch = 1

for i in range(epoch):
    ptr = 0
    for j in range(no_of_batches):
        inp, out = train_input[ptr:ptr+batch_size], train_output[ptr:ptr+batch_size]
        ptr+=batch_size
        sess.run(minimize,{data: inp, target: out})
    
    if i%50 ==0:
        print "Epoch ",str(i)

/tools/anaconda2/envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/ops/gradients.py:90: UserWarning: Converting sparse IndexedSlices to a dense Tensor of unknown shape. This may consume a large amount of memory.
  "Converting sparse IndexedSlices to a dense Tensor of unknown shape. "


Epoch  0


In [9]:
incorrect = sess.run(error,{data: test_input, target: test_output})
print sess.run(prediction,{data: train_input[-10:-1]})
print train_output[-10:-1]
print('Epoch {:2d} error {:3.1f}%'.format(i + 1, 100 * incorrect))

[[ 0.6575278   0.12208451  0.22038771]
 [ 0.49345002  0.30983093  0.19671902]
 [ 0.45673025  0.3403376   0.20293216]
 [ 0.77070981  0.03998085  0.18930939]
 [ 0.46610561  0.33905813  0.19483621]
 [ 0.48033848  0.31919712  0.20046449]
 [ 0.95609027  0.0413406   0.00256915]
 [ 0.46481004  0.3392663   0.1959237 ]
 [ 0.66831338  0.13087931  0.2008073 ]]
[[1, 0, 0], [0, 1, 0], [1, 0, 0], [1, 0, 0], [0, 0, 1], [0, 1, 0], [1, 0, 0], [0, 0, 1], [1, 0, 0]]
Epoch  1 error 44.4%


In [10]:
sess.close()